apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: task-app
  namespace: production
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - task-app.local
      secretName: task-app-tls
  rules:
    - host: task-app.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: task-app
                port:
                  number: 80
